'use strict'

//http状态
export const IS_LOADING = 'IS_LOADING'
export const IS_ERROR = 'IS_ERROR'
export const IS_SUCCESS = 'IS_SUCCESS'
//登陆页面状态
export const GOT_AGREEMENT = 'GOT_AGREEMENT'
export const GOT_VCODE = 'GOT_VCODE'
export const GOT_TOKEN = 'GOT_TOKEN'
export const SPECIAL_TYPE = 'SPECIAL_TYPE'
//资讯页面
export const GOT_NEWSLIST = 'GOT_NEWSLIST'
export const GOT_NEWSDETAIL = 'GOT_NEWSDETAIL'
//产品/服务页面
export const GOT_PRODUCTCATE = 'GOT_PRODUCTCATE'
export const GOT_PRODUCTSLIST = 'GOT_PRODUCTSLIST'
export const GOT_PRODUCTSDETAIL = 'GOT_PRODUCTSDETAIL'
export const GOT_PRODUCTSACCOUT = 'GOT_PRODUCTSACCOUT'
export const SUBMIT_PRODUCTSORDER = 'SUBMIT_PRODUCTSORDER'
//顾问室页面
export const GOT_USERINFO = 'GOT_USERINFO'
export const GOT_SERVICELIST = 'GOT_SERVICELIST'
export const GOT_ADVISORTARGET = 'GOT_ADVISORTARGET'
//我的预约
export const GOT_ORDERLIST = 'GOT_ORDERLIST'
export const GOT_ORDERDETAIL = 'GOT_ORDERDETAIL'
export const ACCEPT_ORDER = 'ACCEPT_ORDER'
export const SEND_FEEDBACK = 'SEND_FEEDBACK'
//工作台历
export const GOT_REMINDSLIST = 'GOT_REMINDSLIST'
export const GOT_REMINDDETAIL = 'GOT_REMINDDETAIL'
export const ADD_REMIND = 'ADD_REMIND'
export const MODIFY_REMIND = 'MODIFY_REMIND'
export const DELETE_REMIND = 'DELETE_REMIND'
//客户管理
export const GOT_CUSTOMERSLIST = 'GOT_CUSTOMERSLIST'
export const GOT_CUSTOMERDETAIL = 'GOT_CUSTOMERDETAIL'
export const ADD_CUSTOMER = 'ADD_CUSTOMER'
export const MODIFY_CUSTOMER = 'MODIFY_CUSTOMER'
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER'
export const GOT_AREATREELIST = 'GOT_AREATREELIST'
export const ADD_COMMUNICATE = 'ADD_COMMUNICATE'
//子公司业绩
export const GOT_PERFORM = 'GOT_PERFORM'
export const GOT_PERFORMDETAIL = 'GOT_PERFORMDETAIL'
export const GOT_PERFORMLIST = 'GOT_PERFORMLIST'
export const GOT_ADVISORLIST = 'GOT_ADVISORLIST'
export const GOT_ADVISORDETAIL = 'GOT_ADVISORDETAIL'
